#!/usr/bin/env bash

#
# This file is loaded from the .bash_profile in ~, but is under version control
# to make it easy to setup new computers like I like it.
#

# Add rvm gems and nginx to the path
export PATH=$PATH:~/.gem/ruby/1.8/bin:/opt/nginx/sbin

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='powerline-plain'
# export BASH_IT_THEME='modern'

# Set my editor and git editor
export EDITOR="atom --wait"
export GIT_EDITOR='atom --wait'

# Don't check mail when opening terminal.
unset MAILCHECK

alias code='cd ~/Code'
alias evo="cd ~/Code/evo/evo"

bind '"[A":history-search-backward'
bind '"[B":history-search-forward'

# APPS
alias sprof='source ~/.bash_profile'
alias prof='atom ~/.bash_profile;atom ~/Code/tgsoverly/scripts/bash-profile'
alias te='open -e'  #textedit
alias f='open .' #open folder in finder
alias vlc='./Applications/VLC.app/Contents/MacOS/VLC'

# RAILS
alias rake-here='bundle exec rake'

# SERVERS
alias postgresql-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias postgresql-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias ftp-start='sudo -s launchctl load -w /System/Library/LaunchDaemons/ftp.plist'
alias ftp-stop='sudo -s launchctl unload -w /System/Library/LaunchDaemons/ftp.plist'
alias redis-start='sudo launchctl start io.redis.redis-server'
alias redis-stop='sudo launchctl stop io.redis.redis-server'

# DOCKER
alias docker-clean='docker stop $(docker ps -a -q);docker rm $(docker ps -a -q);docker rmi $(docker images -q)'

# FOLDER
alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ls='ls -halF'
alias lsc='ls -C'
alias lsf='ls -la | grep ^-'  #files only
alias lsd='ls -la | grep ^d'  #dirs only
alias rds="find . -name '*.DS_Store' -type f -delete"

# Mouse
alias fastmouse='defaults write -g com.apple.mouse.scaling 17'

# Networking
alias openports='sudo lsof -i -P | grep -i "listen"'
alias hosts='s /private/etc/hosts'
alias h='curl -sIX GET -w "Total time: %{time_total} s\n"' #issues GET request, only prints response headers and time it took.

# JAVA
DEFAULT_JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home"
export JAVA_HOME=$DEFAULT_JAVA_HOME
alias jv='java -version'
alias jv6='export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home && jv'
alias jv7='export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home && jv'
alias jv8="export JAVA_HOME=$DEFAULT_JAVA_HOME && jv"

alias g3='gvm use grails 3.0.1'
alias g2='gvm use grails 2.4.3'

# Gradle
export GRADLE_OPTS="-Dorg.gradle.daemon=true"

# Text Editors
alias atom-shell='/Applications/Utilities/Atom.app/Contents/MacOS/Atom'
alias atom='/Applications/Atom.app/Contents/MacOS/Atom'

# Computers
alias pi='ssh pi@overly.me'


# kubernetes
alias ku='kubectl'

# color man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;37m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
export MANWIDTH=200

# PATH
export PATH=.:$PATH #Current directory
export PATH=$PATH:"$HOME/Code/tgsoverly/scripts" #other scripts under version control
export PATH=$PATH:/usr/local/bin #Homebrew

function g(){
  if [ -e grailsw ]
  then
    jv7
    ./grailsw $@
  fi

  if [ -e gradlew ]
  then
    jv8
    ./gradlew $@
  fi
}


# Git Alias from bash it
alias gcl='git clone'
alias ga='git add'
alias gall='git add -A'
alias gus='git reset HEAD'
alias gm="git merge"
alias get='git'
alias gst='git status'
alias gs='git status'
alias gss='git status -s'
alias gl='git pull'
alias gpr='git pull --rebase'
alias gpp='git pull && git push'
alias gup='git fetch && git rebase'
alias gp='git push'
alias gpo='git push origin'
alias gdv='git diff -w "$@" | vim -R -'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcm='git commit -v -m'
alias gci='git commit --interactive'
alias gb='git branch'
alias gba='git branch -a'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gexport='git archive --format zip --output'
alias gdel='git branch -D'
alias gmu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias gg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias ggs="gg --stat"
alias gsl="git shortlog -sn"
alias gw="git whatchanged"

# Load Bash It
source $BASH_IT/bash_it.sh

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh"

# The next line updates PATH for the Google Cloud SDK.
source "$HOME/Applications/google-cloud-sdk/path.bash.inc"

# The next line enables bash completion for gcloud.
source "$HOME/Applications/google-cloud-sdk/completion.bash.inc"

export NVM_DIR="/Users/toverly/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
