#!/usr/bin/env bash

function remap_internal_keyboard() {
  KEYBOARD_ID=$1
  defaults -currentHost write -g "com.apple.keyboard.modifiermapping.${KEYBOARD_ID}-0" -array \
'<dict>
    <key>HIDKeyboardModifierMappingDst</key>
    <integer>-1</integer>
    <key>HIDKeyboardModifierMappingSrc</key>
    <integer>0</integer>
</dict>'
}

# Seil
function remap_caps_lock() {
  defaults write ~/Library/Preferences/org.pqrs.Seil.plist -array '<dict>
  	<key>MigrationUtilitiesCurrentBundleIdentifer</key>
  	<string>org.pqrs.Seil</string>
  	<key>SUFeedURL</key>
  	<string>https://pqrs.org/osx/karabiner/files/seil-appcast.xml</string>
  	<key>SUHasLaunchedBefore</key>
  	<true/>
  	<key>SULastCheckTime</key>
  	<date>2017-05-15T18:35:23Z</date>
  	<key>isCheckUpdate</key>
  	<true/>
  	<key>kResumeAtLogin</key>
  	<true/>
  	<key>sysctl</key>
  	<dict>
  		<key>enable_capslock</key>
  		<integer>1</integer>
  		<key>keycode_capslock</key>
  		<integer>53</integer>
  	</dict>
  </dict>'
}

export SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Set my editor and git editor
export EDITOR="nvim"
export GIT_EDITOR='nvim'

# Use VI key bindings
# Use again when I figure out whey the git prompt makes the cursor funny
# set -o vi
# bind 'set show-mode-in-prompt on'

# Don't check mail when opening terminal.
unset MAILCHECK

# Edit common files
alias econfig="nvim ~"
alias ehosts="nvim /etc/hosts"

bind '"[A":history-search-backward'
bind '"[B":history-search-forward'

# APPS
alias te='open -e'  #textedit
alias f='open .' #open folder in finder
alias vlc='./Applications/VLC.app/Contents/MacOS/VLC'

# RAILS
alias rake-here='bundle exec rake'

# SERVERS
alias postgresql-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias postgresql-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias redis-start='sudo launchctl start io.redis.redis-server'
alias redis-stop='sudo launchctl stop io.redis.redis-server'

# DOCKER
alias docker-clean='docker stop $(docker ps -a -q);docker rm $(docker ps -a -q);docker rmi $(docker images -q)'
alias docker-prune='docker rmi $(docker images -f "dangling=true" -q)'
PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH=$PATH:$HOME/Applications

alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ls='ls -halF'
alias lsc='ls -C'
alias lsf='ls -la | grep ^-'  #files only
alias lsd='ls -la | grep ^d'  #dirs only
alias rds="find . -name '*.DS_Store' -type f -delete"
alias ip='ifconfig | grep "inet "'
alias size10='find . -type d -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'


# Git Alias from bash it
alias gcl='git clone'
alias ga='git add'
alias gall='git add -A'
alias gus='git reset HEAD'
alias gm="git merge"
alias get='git'
alias gst='git status'
alias gs='git status'
alias gss='git status -s'
alias gl='git pull'
alias gpr='git pull --rebase'
alias gp='git push'
alias gpr='git fetch --prune'
alias gpo='git push origin'
alias gcm='git checkout master'
alias gci='git commit --interactive'
alias gb='git branch'
alias gba='git branch -a'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gexport='git archive --format zip --output'
alias gdel='git branch -D'
alias gmu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
alias ggs="gg --stat"
alias gsl="git shortlog -sn"
alias gw="git whatchanged"
alias gl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gaa="git add .;get commit --amend --no-edit"
alias gaap="git add .;get commit --amend --no-edit;git push -f"

# Mouse
alias fastmouse='defaults write -g com.apple.mouse.scaling 17'

# GO
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# Networking
alias openports='sudo lsof -i -P | grep -i "listen"'
alias hosts='s /private/etc/hosts'
alias h='curl -sIX GET -w "Total time: %{time_total} s\n"' #issues GET request, only prints response headers and time it took.

# Gradle
export GRADLE_OPTS="-Dorg.gradle.daemon=true"

# color man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;37m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
export MANWIDTH=200

# PATH
export PATH=.:$PATH #Current directory
export PATH=$PATH:"$SCRIPTS_DIR" #other scripts under version control
export PATH=/usr/local/bin:$PATH #Homebrew

# Load different environment setups
if [ "$ENV_HOME" = "true" ]; then
  source "${SCRIPTS_DIR}/env-home.sh"
fi
if [ "$ENV_WORK" = "true" ]; then
  source "${SCRIPTS_DIR}/env-work.sh"
fi
