#!/usr/bin/env bash
export SCRIPTS_DIR="$( cd "$( dirname "$0" )" && pwd )"

# Set my editor and git editor
export EDITOR="nvim"
export GIT_EDITOR='nvim'

# Use VI key bindings
# Use again when I figure out whey the git prompt makes the cursor funny
bindkey -v
# bind 'set show-mode-in-prompt on'

# Don't check mail when opening terminal.
unset MAILCHECK

# Edit common files
alias econfig="nvim ~"
alias ehosts="nvim /etc/hosts"
alias lconfig='rm -f ~/.config/nvim && rm -f ~/.tmux.conf && ln -s ~/code/dotfiles/nvim/ ~/.config/nvim && ln -s ~/code/dotfiles/my_tmux.conf ~/.tmux.conf'

bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward

# APPS
alias te='open -e'  #textedit
alias f='open .' #open folder in finder

# DOCKER
alias docker-clean='docker stop $(docker ps -a -q);docker rm $(docker ps -a -q);docker rmi $(docker images -q)'
alias docker-prune='docker rmi $(docker images -f "dangling=true" -q)'

export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH=$PATH:$HOME/Applications

alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ls='ls -halF'
alias lsc='ls -C'
alias lsf='ls -la | grep ^-'  #files only
alias lsd='ls -la | grep ^d'  #dirs only
alias rds="find . -name '*.DS_Store' -type f -delete"
alias ip='ifconfig | grep "inet "'
alias size10='find . -type d -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'
alias sprof="source ${HOME}/.zshrc"


# Git Alias from bash it
alias gw="git whatchanged"
alias gaa="git add .;git commit --amend --no-edit"
alias gaap="git add .;git commit --amend --no-edit;git push -f"

# Mouse
alias fastmouse='defaults write -g com.apple.mouse.scaling 17'

# GO
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# Networking
alias openports='sudo lsof -i -P | grep -i "listen"'
alias hosts='s /private/etc/hosts'
alias h='curl -sIX GET -w "Total time: %{time_total} s\n"' #issues GET request, only prints response headers and time it took.

# Gradle
export GRADLE_OPTS="-Dorg.gradle.daemon=true"

# PATH
export PATH=.:$PATH #Current directory
export PATH=$PATH:"$SCRIPTS_DIR" #other scripts under version control
export PATH=/usr/local/bin:$PATH #Homebrew

export USE_OH_MY_ZSH="true"
export ZSH_THEME="sunrise"
